theme: jekyll-theme-tactile

title: 獅子座じゃない人の自由帳
description: 制作後記や独り言など…
google_analytics: G-P1CM10C7RM

url: "https://notleonian.github.io/blog/"
sitemap:
    file: "/sitemap.xml"
    exclude:
    include_posts:
        - "/index.html"
    change_frequency_name: "always"
    priority_name: "1.0"
